name: kivy-ios

on: [push, pull_request]

jobs:
  build_updated_recipes:
    runs-on: macos-latest
    steps:
    - name: Checkout kivy-ios
      uses: actions/checkout@v2
    - name: Set up Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.x
    - name: Install requirements
      run: |
        pip3 install -r requirements.txt
        pip3 install sh
        brew install autoconf automake libtool pkg-config
        brew link libtool
        pip3 install Cython==0.29.10
    - name: Build updated recipes
      run: |
        python3 .ci/rebuild_updated_recipes.py
